### ISSUE TITLE
Installation of chemarr

### ISSUE THREAD

**Issue by shoehangxh** [learningmatter-mit/Chem-prop-pred#2]
When trying to run 
`conda env create -f environment.yml`
of the process in the README

came across the issue
`EnvironmentFileNotFound: '../Chem-prop-pred-main/ChemArr/environment.yml' file not found`

Is there something wrong in the procedure of installation?

**Comment by JurgisR** [comment]
Hi,

Did you manage to first initialize and update the ChemArr submodule with:
`git submodule init`
`git submodule update`

**Comment by shoehangxh** [comment]
Hi,

Yes， I managed to run that two code after run 
`git init`
because it doesn't work without git init.
 I think there may be some error in Git, so I tried to download the repo via Github Desktop, and it remind me about 

`Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.

Would you like to retry cloning ?`

and this will not appear when i cloning other repo, so does it mean that i don't have the permission to some of the file in this repo?

Thank you very much!

**Comment by JurgisR** [comment]
The ChemArr submodule was not made public before and is now. It should be working now without the authentication errors. Tell me if something else is not working.

**Comment by shoehangxh** [comment]
Thank you for your patience!
It worked for me now
